src/Entity/Order.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\OrderRepository;
use App\Type\Rank;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: 'orders')]
#[ORM\UniqueConstraint(fields: ['directorate', 'number'])]
class Order
{
    use IdTrait;
    use TimestampableEntity;

    #[ORM\ManyToOne(targetEntity: Directorate::class, inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private Directorate $directorate;

    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $number = null;

    #[ORM\ManyToOne(targetEntity: Employee::class)]
    #[ORM\JoinColumn(nullable: false)]
    private Employee $author;

    #[ORM\ManyToOne(targetEntity: Position::class)]
    #[ORM\JoinColumn(nullable: false)]
    private Position $authorPosition;

    #[ORM\Column(type: 'rank', nullable: true)]
    private Rank $authorRank;

    #[ORM\Column(type: 'text')]
    private string $title = '';

    #[ORM\Column(type: 'text')]
    private string $text = '';

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $signedAt = null;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'cancelOrders')]
    private ?Order $canceledBy = null;

    #[ORM\OneToMany(mappedBy: 'canceledBy', targetEntity: self::class)]
    #[ORM\OrderBy(['number' => 'ASC'])]
    private Collection $cancelOrders;

    #[ORM\Column(type: 'json')]
    private array $draftData = [];

    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $externalId = null;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $externalUrl = null;

    public function __construct(Employee $author)
    {
        $this->directorate = $author->getDirectorate();
        $this->author = $author;
        $this->authorPosition = $author->getPosition();
        $this->authorRank = $author->getRank();
        $this->cancelOrders = new ArrayCollection();
    }

    public function __toString(): string
    {
        $str = $this->getCaption().' '.$this->title;
        if (mb_strlen($str) > 100) {
            return mb_substr($str, 0, 97).'...';
        }

        return $str;
    }

    public function getCaption(): string
    {
        if (null !== $this->number) {
            return sprintf('Приказ №%s от %s', $this->getNumberString(), $this->signedAt->format('d.m.Y H:i:s'));
        }

        return sprintf('Черновик приказа от %s', $this->createdAt->format('d.m.Y H:i:s'));
    }

    public function getDirectorate(): Directorate
    {
        return $this->directorate;
    }

    public function setDirectorate(Directorate $directorate): self
    {
        $this->directorate = $directorate;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(?int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getNumberString(): string
    {
        return $this->number.'/'.$this->authorPosition->getShortName();
    }

    public function getAuthor(): Employee
    {
        return $this->author;
    }

    public function setAuthor(Employee $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getAuthorPosition(): Position
    {
        return $this->authorPosition;
    }

    public function setAuthorPosition(Position $authorPosition): self
    {
        $this->authorPosition = $authorPosition;

        return $this;
    }

    public function getAuthorRank(): Rank
    {
        return $this->authorRank;
    }

    public function setAuthorRank(Rank $authorRank): self
    {
        $this->authorRank = $authorRank;

        return $this;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getSignedAt(): ?\DateTimeImmutable
    {
        return $this->signedAt;
    }

    public function setSignedAt(?\DateTimeImmutable $signedAt): self
    {
        $this->signedAt = $signedAt;

        return $this;
    }

    public function getCanceledBy(): ?self
    {
        return $this->canceledBy;
    }

    public function setCanceledBy(?self $canceledBy): self
    {
        $this->canceledBy = $canceledBy;

        return $this;
    }

    /**
     * @return self[]
     */
    public function getCancelOrders(): array
    {
        return $this->cancelOrders->toArray();
    }

    public function addCancelOrder(self $cancelOrder): self
    {
        if (!$this->cancelOrders->contains($cancelOrder)) {
            $this->cancelOrders[] = $cancelOrder;
            $cancelOrder->setCanceledBy($this);
        }

        return $this;
    }

    public function removeCancelOrder(self $cancelOrder): self
    {
        if ($this->cancelOrders->removeElement($cancelOrder)) {
            // set the owning side to null (unless already changed)
            if ($cancelOrder->getCanceledBy() === $this) {
                $cancelOrder->setCanceledBy(null);
            }
        }

        return $this;
    }

    public function getDraftData(): array
    {
        return $this->draftData;
    }

    public function setDraftData(array $draftData): self
    {
        $this->draftData = $draftData;

        return $this;
    }

    public function getExternalId(): ?int
    {
        return $this->externalId;
    }

    public function setExternalId(?int $externalId): self
    {
        $this->externalId = $externalId;

        return $this;
    }

    public function getExternalUrl(): ?string
    {
        return $this->externalUrl;
    }

    public function setExternalUrl(?string $externalUrl): self
    {
        $this->externalUrl = $externalUrl;

        return $this;
    }
}

src/Controller/OrderController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Directorate;
use App\Repository\OrderRepository;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/d/{directorateAlias}/orders')]
class OrderController extends AbstractController
{
    #[Route('/')]
    public function index(
        Request $request,
        OrderRepository $orderRepository,
        #[MapEntity(mapping: ['directorateAlias' => 'alias'])]
        Directorate $directorate
    ): Response {
        $orders = $orderRepository->paginateByDirectorate($directorate, page: $request->query->getInt('page', 1));

        return $this->render('order/index.html.twig', [
            'directorate' => $directorate,
            'orders' => $orders,
        ]);
    }

    #[Route('/{number}', requirements: ['number' => '\d+'])]
    public function show(
        OrderRepository $orderRepository,
        #[MapEntity(mapping: ['directorateAlias' => 'alias'])]
        Directorate $directorate,
        int $number
    ): Response {
        $order = $orderRepository->findOneBy(['directorate' => $directorate, 'number' => $number]);
        if (!$order) {
            throw new NotFoundHttpException();
        }

        return $this->render('order/show.html.twig', [
            'directorate' => $directorate,
            'order' => $order,
        ]);
    }

    #[Route('/autocomplete')]
    public function autocomplete(
        Request $request,
        OrderRepository $orderRepository,
        #[MapEntity(mapping: ['directorateAlias' => 'alias'])]
        Directorate $directorate
    ): JsonResponse {
        $result = [];
        $more = false;
        $q = $request->get('q', '');
        $page = $request->query->getInt('page', 1);
        if ($directorate->isRoot()) {
            $directorate = null;
        }
        if (!empty($q)) {
            $orders = $orderRepository->findByDirectorateAndQuery($directorate, $q, 10 * ($page - 1), 11);
            if (count($orders) > 10) {
                $more = true;
            }
            foreach ($orders as $order) {
                $result[] = [
                    'id' => $order->getId(),
                    'text' => sprintf('%s %s', $order, $order->getTitle()),
                ];
            }
        }

        return new JsonResponse([
            'results' => $result,
            'pagination' => ['more' => $more],
        ]);
    }
}

templates/order/export.html.twig
<h1 style="text-align: center">{{ order.caption }}</h1>
<h2 style="text-align: center">{{ order.title }}</h2>
{{ order.text | raw }}
<div style="display: flex; justify-content: space-between">
    <abbr title="{{ order.authorPosition.name }}">{{ order.authorPosition.shortName }}</abbr>
    <span>{{ order.author.user }}</span>
</div>

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Приказы - {{ directorate }}{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('app_default_index') }}">МпЖД</a></li>
            <li class="breadcrumb-item"><a href="{{ path('app_directorate_index', {directorateAlias: directorate.alias}) }}">{{ directorate }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Приказы</li>
        </ol>
    </nav>
    <h1>Приказы - {{ directorate }}</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">{{ knp_pagination_sortable(orders, 'Номер', 'o.number') }}</th>
            <th scope="col">{{ knp_pagination_sortable(orders, 'Заголовок', 'o.title') }}</th>
            <th scope="col">{{ knp_pagination_sortable(orders, 'Дата', 'o.signedAt') }}</th>
            <th scope="col">Автор</th>
        </tr>
        </thead>
        <tbody>
        {% for o in orders %}
            <tr>
                <th scope="row">
                    <a href="{{ path('app_order_show', {directorateAlias: o.directorate.alias, number: o.number}) }}">
                        {% if o.canceledBy %}<del>{% endif %}#{{ o.numberString }}{% if o.canceledBy %}</del>{% endif %}
                    </a>
                </th>
                <th scope="row">
                    <a href="{{ path('app_order_show', {directorateAlias: o.directorate.alias, number: o.number}) }}">
                        {% if o.canceledBy %}<del>{% endif %}{{ o.title }}{% if o.canceledBy %}</del>{% endif %}
                    </a>
                </th>
                <td>{% if o.canceledBy %}<del>{% endif %}{{ o.signedAt | date('d.m.Y H:i:s') }}{% if o.canceledBy %}</del>{% endif %}</td>
                <td>{% if o.canceledBy %}<del>{% endif %}<abbr title="{{ o.authorPosition.name }}">{{ o.authorPosition.shortName }}</abbr> {{ o.author.user }}{% if o.canceledBy %}</del>{% endif %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div>{{ knp_pagination_render(orders) }}</div>
{% endblock %}

templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ order }}{% endblock %}

{% block body %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('app_default_index') }}">МпЖД</a></li>
            <li class="breadcrumb-item"><a href="{{ path('app_directorate_index', {'directorateAlias': order.directorate.alias}) }}">{{ order.directorate }}</a></li>
            <li class="breadcrumb-item"><a href="{{ path('app_order_index', {'directorateAlias': order.directorate.alias}) }}">Приказы</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ order }}</li>
        </ol>
    </nav>
    <h1 style="text-align: center">{{ order.caption }}</h1>
    <h2 style="text-align: center">{{ order.title }}</h2>
    {{ order.text | raw }}
    <div style="display: flex; justify-content: space-between">
        <abbr title="{{ order.authorPosition.name }}">{{ order.authorPosition.shortName }}</abbr>
        <span>{{ order.author.user }}</span>
    </div>
{#    <div class="row justify-content-between">#}
{#        <div class="col-4"><abbr title="{{ order.authorPosition.name }}">{{ order.authorPosition.shortName }}</abbr></div>#}
{#        <div class="col-4">{{ order.author.user }}</div>#}
{#    </div>#}
    {% if order.canceledBy is not null %}
        <p>Отменён: <a href="{{ path('app_order_show', {'directorateAlias': order.canceledBy.directorate.alias, 'number': order.canceledBy.number}) }}">{{ order.canceledBy }}</a></p>
    {% endif %}
    {% if order.cancelOrders %}
        <p>Отменяет:</p>
        <ol>
            {% for cancelOrder in order.cancelOrders %}
                <li><a href="{{ path('app_order_show', {'directorateAlias': cancelOrder.directorate.alias, 'number': cancelOrder.number}) }}">{{ cancelOrder }}</a></li>
            {% endfor %}
        </ol>
    {% endif %}
{% endblock %}